server:
  port: 8090
  servlet:
    session:
      timeout: 6000000
spring:
  datasource:
    username: root
    password: Infra5@Gep0int
    url: jdbc:mysql://xx.xx.xx.xx:3366/ltzjk?autoReconnect=true&useSSL=false
    #url: jdbc:mysql://xx.xx.xx.xx:3366/ltzjk?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 500000

logging:
  file:
    path: C:\Users\Administrator\Documents\logs
